engines:
  eslint:
    enabled: true
    channel: "eslint-2"
ratings:
  paths:
  - lib/*.js
  - lib/**/*.js
  - lib/*.jsx
  - lib/**/*.jsx
  - test/*.js
  - test/**/*.js
  - karma.conf.js
  - gulpfile.babel.js
