/**
 * Action Types of reducers
 */

export const FETCH_META_REQUEST = 'FETCH_META_REQUEST';
export const FETCH_META_FAILURE = 'FETCH_META_FAILURE';
export const FETCH_META_SUCCESS = 'FETCH_META_SUCCESS';

export const FETCH_POSTS_INDEX_REQUEST = 'FETCH_POSTS_INDEX_REQUEST';
export const FETCH_POSTS_INDEX_FAILURE = 'FETCH_POSTS_INDEX_FAILURE';
export const FETCH_POSTS_INDEX_SUCCESS = 'FETCH_POSTS_INDEX_SUCCESS';

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';

export default {
  FETCH_META_REQUEST,
  FETCH_META_FAILURE,
  FETCH_META_SUCCESS,
  FETCH_POSTS_INDEX_REQUEST,
  FETCH_POSTS_INDEX_FAILURE,
  FETCH_POSTS_INDEX_SUCCESS,
  FETCH_POST_REQUEST,
  FETCH_POST_FAILURE,
  FETCH_POST_SUCCESS,
};
